Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/bootstrap.js.coffee, app/assets/javascripts/top.coffee, app/assets/stylesheets/bootstrap_and_overrides.css, app/assets/stylesheets/normalize.css, app/assets/stylesheets/top.scss, app/controllers/top_controller.rb, app/helpers/top_helper.rb, app/views/top/index.html.erb, config/locales/en.bootstrap.yml, config/routes.rb, test/controllers/top_controller_test.rb
#8　以下の対応しました。
- topのコントローラ・ビューの作成
- bootstrapのgemインストール・初期設定
- routes.rbにroot top#indexの設定追加
=> トップページのコントローラ・ビューを作成しました。

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/application.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/locales/devise.ja.yml, config/locales/ja.yml, config/locales/model.ja.yml, config/routes.rb, db/migrate/20170612093048_devise_create_users.rb, db/migrate/20170612094300_add_name_to_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
=> ユーザ機能を追加しました

app/models/question.rb, app/models/user.rb, db/migrate/20170611135738_create_questions.rb, db/schema.rb, test/fixtures/questions.yml, test/models/question_test.rb
#4 
タイトル：`title:string`
本文：`content:text`
user.rbに
`has_many :questions, dependent: :destroy`、
question.rbに
`belongs_to :user`
を追加。
userモデルのtitle,contentに必須チェックを追加
```
validate :title, presence: true
validate :content, presence: true
```
=> 【Fixed】質問モデルをユーザーモデルと関連付けて作成

Gemfile, Gemfile.lock, config/environments/production.rb
#17 
　　以下、heroku login create時のコマンド結果です。
```
heroku create   Creating app... done, ⬢ hidden-scrubland-80950
https://hidden-scrubland-80950.herokuapp.com/ | 
https://git.heroku.com/hidden-scrubland-80950.git
```
=> 【Fixed】heroku login createを実施する

Gemfile, Gemfile.lock, app/models/user.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, config/routes.rb, db/migrate/20170613010733_add_confirmable_to_devise.rb, db/schema.rb
=> メール認証機能を追加しました

app/controllers/answers_controller.rb, app/views/answers/edit.html.erb
#30 
`answer_controller.rb`の`#update`のtypoを修正
`view/answer/edit.html.erb`の`#update`のtypoを修正
=> 【Fixed】回答の編集ができないバグを修正

Gemfile, Gemfile.lock
=> 【Fixed】Add debug gem

app/assets/javascripts/users.coffee, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/devise/registrations/edit.html.erb, app/views/layouts/application.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb, db/schema.rb, test/controllers/users_controller_test.rb
=> ユーザ一覧ページ作成、マイページ修正

app/assets/javascripts/likes.coffee, app/assets/stylesheets/likes.scss, app/controllers/likes_controller.rb, app/helpers/likes_helper.rb, app/models/like.rb, app/models/question.rb, app/models/user.rb, db/migrate/20170616044019_create_likes.rb, db/schema.rb
=> 【Fixed】お気に入り機能の作成(1)

app/helpers/application_helper.rb, app/views/users/show.html.erb
#42 
ユーザー一覧の貢献度タブで閲覧可能。`application_helper`に実装。
=> [FIxed]Add user contribution function

config/locales/model.ja.yml
=> [Fixed]Translate question models and answer models

app/assets/stylesheets/questions.scss, app/helpers/application_helper.rb, app/views/answers/_form.html.erb, app/views/answers/_index.html.erb, app/views/questions/show.html.erb
#56 
- お気に入りボタンを作成
- サイズ32×32の画像を表示するヘルパーメソッドを作成
- その他stackoverflow風にhtml,css修正
=> 【一旦Fixed】質問詳細のデザイン作り込み

app/assets/stylesheets/tags.scss, app/controllers/tags_controller.rb, app/helpers/tags_helper.rb, app/views/tags/index.html.erb, config/routes.rb
#60 
タブ切り替えの表示がおかしいですが、大体タブ一覧ページを作り込みました。
・人気、名前、新規タブと、表示内容作成
残課題
・タブの表示内容は合っているが、各タブの内容がブロック状態(?)で表示位置が狙いと違う。
・タブの下線が重なっていて、一部太くなっている。
その他
・routesの二重定義削除。resourcesで定義。
=> [仮Fixed]Issues/#60

app/controllers/answers_controller.rb, app/controllers/questions_controller.rb, app/views/answers/_form.html.erb, app/views/answers/edit.html.erb
=> [Fixed]不要なrespond_toの削除

app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/views/users/index.html.erb
=> issue#65 ユーザー一覧のページデザイン作りこみ

app/assets/stylesheets/application.css, app/views/users/index.html.erb
issue#58 ヘッダーのCSS修正とユーザー一覧画面の修正をしました
=> issue#58 ヘッダーのCSS修正とユーザー一覧画面の修正をしました

app/models/user.rb
#69 
上記リンクのコメントを参照ください。rails c での検証方法とロジック修正前後の結果が載っています。
そちら確認いただき問題なければクローズでお願いします。
=> [Fixed] find_for_facebook_oauth method

app/assets/javascripts/questions.coffee, app/assets/stylesheets/questions.scss, app/models/user.rb, app/views/answers/_vote.html.erb, app/views/answers/edit.html.erb, app/views/questions/_vote.html.erb, app/views/questions/edit.html.erb, app/views/questions/index.html.erb, app/views/questions/new.html.erb, app/views/questions/show.html.erb
#77 
* question.scssの全てのCSSセレクタについて,ラッパークラスを被せ、user.scssの影響を受けないようにした。
* 上記修正でマークダウンのjsがなぜか動かなくなったので,DOMレンダリング時にturbolinksを呼ぶよう修正
=> [Fixed] 重複CSSの修正

app/assets/stylesheets/questions.scss, app/controllers/answers_controller.rb, app/controllers/application_controller.rb, app/controllers/questions_controller.rb, app/helpers/application_helper.rb, app/helpers/devise_helper.rb, app/models/answer.rb, app/views/answers/_index.html.erb, app/views/layouts/application.html.erb, app/views/questions/_form.html.erb, app/views/questions/show.html.erb, config/locales/devise.ja.yml, config/routes.rb
#43 
- rootをquestions#indexに変更（top#indexからログインすると質問ボタンが表示されないため
- questions_controller:非ログイン時はindex, showのみできるよう変更
- answers_controller:非ログイン時は回答投稿・編集等できないように変更
- answerモデル:本文必須入力化
#73 
- ログイン成功時等フラッシュメッセージ追加
- 入力チェックに引っかかった場合フラッシュメッセージ追加
=> 【Fixed】非ログイン時制御、フラッシュメッセージの追加

app/assets/javascripts/application.js, app/assets/javascripts/tags.coffee, app/assets/stylesheets/tags.scss, app/controllers/tags_controller.rb, app/helpers/tags_helper.rb, app/views/tags/index.html.erb, vendor/assets/javascripts/tag-it.js, vendor/assets/stylesheets/jquery.tagit.css, vendor/assets/stylesheets/tagit.ui-zendesk.css
#86 
タグindexファイル、タグコントローラ、タグヘルパー、タグ関連jsのコメント削除
=> [Fixed]delete comments

app/assets/javascripts/answers.coffee, app/assets/stylesheets/answers.scss, app/assets/stylesheets/questions.scss, app/models/answer.rb, app/models/question.rb
=> [Fixed]Delete unuseful file and comments

app/views/devise/registrations/edit.html.erb, config/environments/development.rb
/app/views/devise/registration.html.erbのn+1問題を修正しました
=> マイページのN+1問題
